### 1 Exercise

In [1]:
import numpy as np

### 2 Exercise

In [7]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3 Exercise

In [8]:
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 4 Exercise

In [11]:
arry_10_49 = np.arange(10,50)
arry_10_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 5 Exercise

In [15]:
array_3x3 = np.arange(0,9).reshape(3,3)
array_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 6 Exercise

In [39]:
sample_array = np.array([1,2,0,0,4,0])
non_zero_indices = np.nonzero(sample_array)
non_zero_indices

(array([0, 1, 4]),)

### 7 Exercise

In [22]:
eye_array = np.eye(3,3)
eye_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 8 Exercise

In [26]:
array_3x3x3_random = np.random.random([3,3,3])
array_3x3x3_random

array([[[0.12379207, 0.69087147, 0.10136587],
        [0.35743772, 0.16754372, 0.85680551],
        [0.93182235, 0.96066444, 0.40320385]],

       [[0.67455003, 0.70385196, 0.30448393],
        [0.0586012 , 0.557837  , 0.45591982],
        [0.00135771, 0.02491673, 0.90319179]],

       [[0.37948631, 0.65574007, 0.30367054],
        [0.49277111, 0.84591656, 0.89397688],
        [0.33386483, 0.4449919 , 0.73557861]]])

### 9 Exercise

In [40]:
array_10x10_random = np.random.random([10,10])
array_10x10_random.min()
array_10x10_random.max()

0.9931168553752098

### 10 Exercise

In [35]:
array_30_random = np.random.random(30)
array_30_random.mean()

### 11 Exercise

In [65]:
array_5x5 = np.diag(v = np.arange(1,5), k = -1)
array_5x5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 12 Exercise

In [66]:
#tbd
standard_array = np.arange(5,5)
(standard_array-standard_array.mean())/standard_array.std()

/var/folders/rd/g86s3t0n2qg0z79f8ywnk8ym0000gn/T/ipykernel_86448/1855677372.py:2: RuntimeWarning: Mean of empty slice.
  (standard_array-standard_array.mean())/standard_array.std()
/Users/lukasbauerschmidt/opt/anaconda3/envs/DA_Env/lib/python3.9/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/lukasbauerschmidt/opt/anaconda3/envs/DA_Env/lib/python3.9/site-packages/numpy/core/_methods.py:265: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/lukasbauerschmidt/opt/anaconda3/envs/DA_Env/lib/python3.9/site-packages/numpy/core/_methods.py:223: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
/Users/lukasbauerschmidt/opt/anaconda3/envs/DA_Env/lib/python3.9/site-packages/numpy/core/_methods.py:257: RuntimeWarning: invalid value encountered in double_scalars


array([], dtype=float64)

### 13 Exercise

In [87]:
random_6x6_1 = np.random.random([4,4])
random_6x6_2 = np.random.random([4,4])

intersection_array = np.intersect1d(random_6x6_1, random_6x6_2)
intersection_array

array([], dtype=float64)

### 14 Exercise

In [90]:
random10vector_1 = np.random.random(10)
random10vector_1.sort()
random10vector_1

array([0.05492034, 0.05873429, 0.23726912, 0.25403007, 0.27454819,
       0.4149564 , 0.7017094 , 0.71043547, 0.73527635, 0.99193801])

### 15 Exercise

In [123]:
import random

np.random.seed(1000)
random10vector_2 = np.random.random(10)
random10vector_2[random10vector_2.argmax()] = 1
random10vector_2

array([0.65358959, 0.11500694, 1.        , 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

### 16 Exercise

In [287]:
#research: perform math functions for each item in array!
#np.random.seed(1000)
random2x2vector = np.arange(0,4).reshape(2,2)
random2x2vector

array([[0, 1],
       [2, 3]])

In [212]:
random2x2vector.mean(axis=1,keepdims=1)

array([[0.5],
       [2.5]])

In [221]:
random2x2vector - random2x2vector.mean(axis=1,keepdims=1)

array([[-0.5,  0.5],
       [-0.5,  0.5]])

### 17 Exercise

In [301]:
Z = np.arange(10000)
np.random.shuffle(Z)
n=-5
Z[np.argsort(Z)]

array([   0,    1,    2, ..., 9997, 9998, 9999])

### 18 Exercise