### 1 Exercise

In [1]:
import numpy as np

### 2 Exercise

In [7]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3 Exercise

In [8]:
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 4 Exercise

In [11]:
arry_10_49 = np.arange(10,50)
arry_10_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 5 Exercise

In [322]:
array_3x3 = np.arange(0,9).reshape(3,3)
array_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 6 Exercise

In [323]:
sample_array = np.array([1,2,0,0,4,0])
non_zero_indices = np.nonzero(sample_array)
non_zero_indices

(array([0, 1, 4]),)

### 7 Exercise

In [22]:
eye_array = np.eye(3,3)
eye_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 8 Exercise

In [26]:
array_3x3x3_random = np.random.random([3,3,3])
array_3x3x3_random

array([[[0.12379207, 0.69087147, 0.10136587],
        [0.35743772, 0.16754372, 0.85680551],
        [0.93182235, 0.96066444, 0.40320385]],

       [[0.67455003, 0.70385196, 0.30448393],
        [0.0586012 , 0.557837  , 0.45591982],
        [0.00135771, 0.02491673, 0.90319179]],

       [[0.37948631, 0.65574007, 0.30367054],
        [0.49277111, 0.84591656, 0.89397688],
        [0.33386483, 0.4449919 , 0.73557861]]])

### 9 Exercise

In [40]:
array_10x10_random = np.random.random([10,10])
array_10x10_random.min()
array_10x10_random.max()

0.9931168553752098

### 10 Exercise

In [35]:
array_30_random = np.random.random(30)
array_30_random.mean()

### 11 Exercise

In [324]:
array_5x5 = np.diag(v = np.arange(1,5), k = -1)
array_5x5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 12 Exercise

In [347]:
#tbd
standard_array = np.random.random((5,5))
(standard_array-np.mean(standard_array))/np.std(standard_array)

array([[-0.7614271 , -0.60667219,  0.16105211,  1.15914039, -1.88430177],
       [ 1.14831447,  0.33825959,  1.39364711, -0.29814069, -0.613813  ],
       [-0.7621135 ,  1.13852966,  0.58607663, -1.48234749,  0.42570193],
       [-1.58821002,  0.31345455,  0.6823654 ,  1.05538506,  0.8436824 ],
       [ 0.05609864, -1.56993912, -1.05955772,  1.47232981, -0.14751512]])

### 13 Exercise

In [87]:
random_6x6_1 = np.random.random([4,4])
random_6x6_2 = np.random.random([4,4])

intersection_array = np.intersect1d(random_6x6_1, random_6x6_2)
intersection_array

array([], dtype=float64)

### 14 Exercise

In [90]:
random10vector_1 = np.random.random(10)
random10vector_1.sort()
random10vector_1

array([0.05492034, 0.05873429, 0.23726912, 0.25403007, 0.27454819,
       0.4149564 , 0.7017094 , 0.71043547, 0.73527635, 0.99193801])

In [370]:
#np.sort(np.random.randint(-10,10, (1,10)))
#np.random.random([10,10])
#np.random.randint(-10,10, 10)
#np.arange(-10,10).reshape(10)

array([0.68949477, 0.95526214, 0.71621562, 0.07526281, 0.89083729,
       0.86110591, 0.246944  , 0.90368397, 0.17340525, 0.60753843])

### 15 Exercise

In [123]:
import random

np.random.seed(1000)
random10vector_2 = np.random.random(10)
random10vector_2[random10vector_2.argmax()] = 1
random10vector_2

array([0.65358959, 0.11500694, 1.        , 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

### 16 Exercise

In [287]:
#research: perform math functions for each item in array!
#np.random.seed(1000)
random2x2vector = np.arange(0,4).reshape(2,2)
random2x2vector

array([[0, 1],
       [2, 3]])

In [212]:
random2x2vector.mean(axis=1,keepdims=1)

array([[0.5],
       [2.5]])

In [221]:
random2x2vector - random2x2vector.mean(axis=1,keepdims=1)

array([[-0.5,  0.5],
       [-0.5,  0.5]])

### 17 Exercise

In [398]:
Z = np.arange(10000)
np.random.shuffle(Z)
print(Z[np.argsort(Z)[-7:]])

[9993 9994 9995 9996 9997 9998 9999]


### 18 Exercise

In [397]:
random_arrray = np.random.randint(1,10,[1,10])
random_arrray

array([[2, 6, 2, 6, 5, 2, 7, 5, 4, 3]])

In [396]:
a=np.where(random_arrray>4, random_arrray**2, random_arrray)
a

array([[ 3, 81, 25, 49,  1, 36, 25,  1, 49,  1]])